food_recipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('accounts/',include('accounts.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('',views.home, name="home"),
    path('', views.Store, name='store'),
    path('category/<slug:category_slug>/', views.Store, name='category_product'),
    path('create_menu/',views.create_recipe, name='create_menu'),
    path('update_recipe/<int:product_id>/', views.update_recipe, name='update_recipe'), 
    path('product_details/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'), 
    path('delete_recipe/<int:recipe_id>/', views.Delete_recipe, name='delete_recipe'), 
    path('search/',views.search, name='search'),
    path('Product/details/Review/<slug:category_slug>/<slug:product_slug>/', views.product_detail_review, name="product_details_reviews"),
]

store/models.py
from django.db import models
from category.models import Category
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=3)

    product_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100,unique=True)
    description = models.TextField(max_length=500, blank=True)
    ingredients = models.TextField(max_length=500,blank=True)
    instructions = models.TextField(max_length=500,blank=True)
    image = models.ImageField(upload_to='photos/products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,default=1, related_name='user_data')
    
    
    def __str__(self):
        return self.product_name


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    user =  models.ForeignKey(User, on_delete = models.CASCADE)
    comment = models.TextField(max_length=500)
    rating = models.FloatField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return str(self.id)

store/forms.py
from django import forms
from . models import Product, Review



class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'description', 'ingredients', 'instructions','image','category', 'price']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm
from . models import Product
from django.http import Http404
from django.contrib.auth.decorators import login_required
from category.models import Category
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render
from store.models import Product
from category.models import Category


# def home(request):
#     product = Product.objects.all()
#     cat = Category.objects.all()
#     context =  {'product' : product, 'category':cat}
#     return render(request,'index.html', context)

# ==============================================================


def Store(request, category_slug = None):
    product=None
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        product = Product.objects.filter(category=category)
    else:
        product = Product.objects.all()
    cat = Category.objects.all()
    context =  {'product' : product, 'category':cat}
    return render(request,'index.html', context)



@login_required
def create_recipe(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        # print('baire=========')
        if form.is_valid():
            # print('valid--------------')
            slugg = form.cleaned_data['product_name']
            slugg=slugg.replace(" ","_")
            # print('-==========------dk', slugg)
            if Product.objects.filter(slug=slugg).exists():
                raise Http404("The requested slug does not exist.")
            else:
                if request.user.is_authenticated:
                    title = form.cleaned_data['product_name']
                    description = form.cleaned_data['description']
                    ingredient = form.cleaned_data['ingredients']
                    instruction = form.cleaned_data['instructions']
                    image = form.cleaned_data['image']
                    slug = slugg
                    category = form.cleaned_data['category']
                    price = form.cleaned_data['price']
                    product = Product(product_name = title, description=description, ingredients=ingredient, instructions=instruction,image=image,
                                slug=slug, category=category, author = request.user, price = price)
                    product.save()
                    return redirect('home') 
                else:
                    return redirect(request,'lonin')
    else:
        form = ProductForm()
    return render(request, 'menu_form.html', {'form' : form})



@login_required
def update_recipe(request, product_id):
    recipe = Product.objects.get(pk=product_id)
    form = ProductForm(instance=recipe)
    
    if recipe.author == request.user:
        if request.method == 'POST':
            form = ProductForm(request.POST, instance=recipe)
            if form.is_valid():
                slugg = form.cleaned_data['product_name']
                slugg=slugg.replace(" ","_")
                title = form.cleaned_data['product_name']
                description = form.cleaned_data['description']
                ingredient = form.cleaned_data['ingredients']
                instruction = form.cleaned_data['instructions']
                image = form.cleaned_data['image']
                slug = slugg
                category = form.cleaned_data['category']
                product = Product(product_name = title, description=description, ingredients=ingredient, instructions=instruction,image=image,
                slug=slug, category=category, author = request.user)
                recipe.delete()
                product.save()
                return redirect('profile') 
        else:
            form = ProductForm(instance=recipe)
        return render(request, 'update_recipe.html', {'form': form, 'recipe': recipe})
    else:
        return redirect('home')

def product_detail(request, category_slug, product_slug):
    
    single_product = Product.objects.get(category__slug = category_slug, slug=product_slug)
    return render(request, 'product_details.html', {'recipe':single_product})

@login_required
def Delete_recipe(request, recipe_id):
    recipe = Product.objects.get(pk=recipe_id)
    if request.user == recipe.author:
        user_profile = User.objects.get(username=recipe.author.username)
        user_recipe = Product.objects.filter(author=user_profile)
        
        context =  {'profile' : user_profile, 'user_recipe':user_recipe}
        recipe.delete()
        return render(request, 'accounts/profile.html', context)
    else:
        return redirect(request, 'login')
    


def search(request):
    products=[]
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.filter(ingredients__icontains=keyword)
            # print('==----===', products)
    return render(request, 'index.html', {'product': products})



def product_detail_review(request, category_slug, product_slug):
    
    single_product = Product.objects.get(category__slug = category_slug, slug=product_slug)
   
    return render(request, 'details_review.html', {'products':single_product})

store/templates/details_review.html
{% extends 'base.html' %}

{% block body%}

            <div class="row-lg">

           
           
              <div class="cards-img">
                <div class="card-img">
                  <a class="img-wrap"> <img src="{{products.image.url}}"> </a>
                </div>
              </div>   

              <div class="info-body">
                 <div class="card-info-details">
                    <p> <h2> {{products.product_name}} </h2></p>
                    <p> {{products.category}}</p>
                    <p>TK. {{products.price}}</p>
                  </div>    

                  <!-- card-info-details ended -->

                  <div class="review-sections">

                     <h2 class="review-heading">REVIEW</h2>

                     <div class="privious-review-section">
                           <div class="reviewer">
                               <p><img class="reviewer-profile" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkN9BY5gyMxjAxe5I3SbK0L_EJf8t-TtE4fJwH_JpMKQ&s" alt="profile Avatar"></p>

                               <div class="fa-star-icon">
                                <p class="star-icon"><i  class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></p>                                
                               </div>

                           </div>

                           <div class="review-message">
                                 <h3 class="user-name-date">sohag - Oct. 18,23,3:18 am</h3>
                                 <p class="user-review">amazing</p>
                           </div>
                     </div>


                     

                     <!-- privious review section ended -->

                     <div class="current-reviews-sections">

                      <h4>Write a review</h4>

                      <form action="POST" action="#">
                        {% csrf_token %}

                        <input type="hidden" name="prod_id" value="{{products.id}}">
                        <div class="product-ratings">

                          <label for="star-1" class="label"><i class="fa fa-star"></i></label>
                          <input type="radio" class="input1" id="star-1" name="rating" value="1" >

                          <label for="star-2" class="label"><i class="fa fa-star"></i></label>
                          <input type="radio" class="input1" id="star-2" name="rating" value="2" >

                          <label for="star-3" class="label"><i class="fa fa-star"></i></label>
                          <input type="radio" class="input1" id="star-3" name="rating" value="3" >

                          <label for="star-4" class="label"><i class="fa fa-star"></i></label>
                          <input type="radio" class="input1" id="star-4" name="rating" value="4" >

                          <label for="star-5" class="label"><i class="fa fa-star"></i></label>
                          <input type="radio" class="input1" id="star-5" name="rating" value="5" checked>

                        </div>

                        <div class="form-group-text">
                          <div class="text"> Your Review <sup class="required">*</sup></div>
                          <textarea name="coment" id="comment" cols="20" rows="6"></textarea>
                        </div>

                        <div class="form-group-button">
                          <button type="submit" class="btn btn-primary"> Send Your Review</button>
                        </div>


                      </form>

                     </div>  
                     <!-- current reviews sections ended -->
                  </div>  

                  <!-- review-sections ended -->

                  <div class="order-section">

                  </div>

                  <!-- order sections ended -->

                 </div> <!-- info-body ended -->
            </div>




            <style>
                
                *{
                  margin: 0;
                  padding: 0;
                  box-sizing: border-box;
                }

                .row-lg{
                  width: 100%;
                  height: auto;
                  padding-bottom: 100px; 
                  /* background-color: antiquewhite; */
                
                }

                .card-img{
                  /* display: flex; */
                  width: 100%;
                  text-align: center;
                  background-color: aliceblue;
                }
                
                .img-wrap img{
                  border-radius: 30px;
                  width: 50%;
                  height: 400px;
                  padding: 20px;
                }

                /* information design start from here */
                    .info-body{
                      position: relative;
                      width: 100%;
                      background-color: white;
                      text-align: left
                    }

                    .card-info-details{
                     position: sticky;
                      width: 20%;
                      margin-left: 20px;
                      padding: 10px;
                      text-align: justify;
                      background-color: white;
                      border: 1px solid white;
                      box-shadow: 2px 2px 3px 3px rgba(182, 176, 176, 0.3);
                      text-align: center;
                    }


                    .card-info-details p{
                      padding: 10px;
                      font-size: 1.2rem;
                    }

                    .card-info-details p span{
                      font-weight: bold;
                    }

                    /*  review sections start from here */

                    .review-sections {
                        position: absolute;
                        width: 50%;
                        
                        /* background-color: rgb(226, 134, 13); */
                        left: 22%;
                        top: 0;
                    }

                    .review-heading{
                        text-align: center;
                        padding: 20px;
                        font-size: 2rem;
                    }

                    .privious-review-section{
                      padding: 20px;
                      position: relative;
                      margin: 10px;
                      margin-bottom: 30px;
                      /* border: 1px solid gray; */
                      height: 200px;
                      border-radius: 10px;
                    }

                    .reviewer{
                      position: absolute;
                      left: 0;
                    }

                    .reviewer p{
                      padding-left: 10px;
                    }

                    .review-message{
                      position: absolute;
                      left: 30%;
                    }

                    .fa-star-icon{
                      padding-left: 25%;
                    }

                    .star-icon{
                      color: rgb(230, 196, 6);
                      padding-left: 20px;
                    }





                    /* review sections ended here */


                    .info-body{
                         content: "";
                         display: block;
                         clear: both;
                    }



                /* information design ended here */


                /* revies sections start */

                .input1{
                  display: none;
                }

                .label{
                  cursor: pointer;
                  padding: 0 0.1em;
                  font-size: 3rem;
                }

                .fa-star{
                  color: orange;
                }

                .input1:checked ~ .label .fa-star{
                  color: #ddd;
                }

                .rating-group:hover .label .fa-star{
                  color: orange;
                }

                .input1:hover ~ .label .fa-star{
                  color: #ddd;
                }

                textarea {
                  width: 100%;
                  resize: none;
                  padding: 10px;
                  height: 100px;
                }

                .btn-primary{
                  padding: 5px;
                  border-radius: 5px;
                  outline: none;
                  border: none;
                  background-color: green;
                  color: white;

                }

                .btn-primary:hover{
                  transform: scale(1.2);
                }

                /* reviews sections ended */


                .row-lg::after{
                  content: "";
                  display: block;
                  clear: both;
                }
            </style>
          

{% endblock%}

store/templates/index.html
{% extends 'base.html' %}

{% load static %}





{% block body %}

<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name">
<div class="containers">

{% if product %}

<header class="section-heading">
	<h3 class="section-title">Popular Recipe</h3>
</header><!-- sect-heading -->

<div class="rows">
	<div class="row">

		{% for recipe in product %}
		
		
			<div class="card-body">

				<div class="card-body-contains">
					<div class="card-img">
						<a href="{% url 'product_detail' recipe.category.slug recipe.slug %}" class="img-wrap"> <img src="{{recipe.image.url}}"> </a>
					</div>
					
					
					<div class="card-info">
						<div class="product-info-card">
							<div class="name"><a class="title-a">{{recipe.product_name}}</a></div>
							<div class="category"><a  class="category-a">{{recipe.category}}</a></div>
							<div class="price"><a class="price-a">Tk: {{recipe.price}}</a></div>
						</div>
	
						<div class="star">
							<div class="star-body"><a class="price-a">star</a></div>
							<div class="card-button">
								<button class="cook-button"><a href="{% url 'product_detail' recipe.category.slug recipe.slug %}" class="img-wrap"> Cook </a></button>
								<button class="details-button"><a href="{% url 'product_details_reviews' recipe.category.slug recipe.slug %}">Details</a></button>
							</div>
						</div>
	
					</div>	
				</div>


			
	

			</div>


		{% endfor %}
	</div> <!-- row.// -->

</div>

{% else %}
<h2> Recipe List is Empty </h2>

{% endif%}

</div><!-- container // -->

</section>


<style>


	
	*{
		margin: 0;
		padding: 0;
		box-sizing: border-box;
	}

  h3{
	background-color: antiquewhite;
	width: 100%;
	height: 40px;
	text-align: center;
	/* padding: 20px; */
	padding-top: 10px;
	margin-bottom: 20px;
	font-weight: bold;
  }


  .row{
	display: flex;
	flex-wrap: wrap;

	left: 30px;
  }

  .card-body{
	width: 30%;
	/* padding: 15px; */
	height: 450px;
	margin-left: 30px;
	margin-bottom: 30px;
	border: 1px solid gray;
	box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
	transition: 0.5;
	border-radius: 10px;
  }

  .card-body-contains{
	height: 400px;
  }



  .card-img img {
	/* box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.5); */
    width: 100%;
    height: 300px;
    display: block;
	border-radius: 10px 10px  0 0;
	margin-bottom: 10px;
	transition: 0.4s;
}

.card-img img:hover{
       /* width: 23%; */
	   box-shadow: 3px 4px 15px 6px rgba(0, 0, 0, 0.5);
  }

  .card-info{
	/* background-color: rgb(141, 82, 82); */
	padding: 15px;
	position: relative;
  }

  .product-info-card{
    padding: 10px;
    position: absolute;
    width: 50%;
      /* background-color: antiquewhite; */
    left: 0;

  }

  .product-info-card div{
    margin: 5px;
  }

  .product-info-card .name {
    font-size: 1.5rem;
  }

  .product-info-card .category{
    font-size: 0.7rem;
  }

  .star{
    position: absolute;
    width: 50%;
    /* background-color: white; */
    right: 0;
    text-align: center;
  }

  .star::after{
	content: "";
	display: block;
	clear: both;
  }

  .star-body{
	height: 100px;
  }

  .star .card-button{
	position: absolute;
	bottom: 0;
  }

  .star .card-button button{

	cursor: pointer;
	background-color: green;
	color: white;
	border-radius: 5px;
	outline: none;
	border: none;
  }
  .star .card-button button a{
	margin: 0px;
	padding: 5px;
	cursor: pointer;
	background-color: green;
	color: white;
	border-radius: 5px;
	outline: none;
	border: none;
  }

  .product-info-card::after{
	content: "";
	display: block;
	clear: both;
  }

  .cards::after{
	content: "";
	display: block;
	clear: both;
  }

  

</style>



{% endblock %}

store/templates/menu_form.html
{% extends 'base.html' %}

{% block body%}
<section class="section-containers">
      <!-- ============================ COMPONENT REGISTER   ================================= -->
      <div class="card-sections">
        <div class="card-body">
          <header>
            <h4 class="card-title"></h4>
          </header>
          <div class="form-div">
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-row">
                <div class="col form-group">
                  <label>Item name</label>
                  <br/>
                  <p class="product-class">{{form.product_name}}</p>
                  <br>
                </div>
              </div>

              <div class="form-row">
                <div class="col form-group">
                  <label>Price</label>
                  <br/>
                  <p class="product-class">{{form.price}}</p>
                  <br>
                </div>
              </div>
  
  
                <div class="col form-group">
                  <label>Category</label>
                  <br/>
                  <p class="product-class">{{ form.category }}</p>
                </div>
                <!-- form-group end.// -->
                <div class="col form-group">
                 
                  <label>Description</label>
                  <br/>
                  <p class="product-class">{{form.description}}</p>
           
                <!-- form-group end.// -->
              </div>
              <!-- form-row end.// -->
              <div class="form-group">
                <label>Ingredients</label>
                <br/>
                  <p class="product-class">{{form.ingredients}}</p>
              </div>
              <!-- form-group end.// -->
  
           
                <div class="form-group col-md-6">
                  <label>Instructions</label>
                  <br/>
                   <p class="product-class">{{form.instructions}}</p>
                  <br/>
                </div>
                <!-- form-group end.// -->
                <div class="form-group col-md-6">
                  <label>image</label>
                  <br/>
             
                  <p class="product-class">{{form.image}}</p>
                </div>
                <!-- form-group end.// -->
              
              <div class="form-group">
                <button type="submit" class="btn-block">
                  Submit
                </button>
              </div>
              <!-- form-group// -->
            </form>
          </div>


        </div>
        <!-- card-body.// -->
      </div>
      <!-- card .// -->

      <br /><br />
      <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    </section>


    <style>

      *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      .section-containers{
        position: relative;
        width: 100%;
        background-color: azure;
        /* display: flex; */
        text-align: center;
        height: 850px;
      }

      .card-body{
        position: absolute;
        width: 50%;
        display: flex;
        left: 25%;
        background-color: rgb(230, 238, 238);
        flex: left;
      }

      .form-div{
        /* background-color: rebeccapurple; */
        width: 100%;
      }

      input#id_price{
        width: 310px;
        padding: 10px;
        outline: none;
        border: none;
        box-shadow: 2px 2px 2px 2px rgba(20, 20, 20, 0.6);        
      }

      input#id_product_name{
        width: 310px;
        padding: 10px;
        outline: none;
        border: none;
        box-shadow: 2px 2px 2px 2px rgba(20, 20, 20, 0.6);
      }

      input#id_instructions{
        width: 310px;
        padding: 10px;
        outline: none;
        border: none;
        box-shadow: 2px 2px 2px 2px rgba(20, 20, 20, 0.6);
      }
     
      .product-class {
    /* Add your styles here */
    /* padding: 8px; */
    font-size: 16px;
    color: #333;
    line-height: 1.5;
    /* Add more styles as needed */
}

   .btn-block{
    width: 100px;
    margin: 15px;
    padding: 5px;
    background-color: green;
    color: white;
    cursor: pointer;
   }


    </style>
{% endblock%}

store/templates/product_details.html
{% extends 'base.html' %}

{% block body%}

            <div class="row">

           
           
              <div class="cards-img">
                <div class="card-img">
                  <a class="img-wrap"> <img src="{{recipe.image.url}}"> </a>
                </div>
              </div>   

              <div class="info-body">
                 <div class="card-info-details">
                    <p> <span>Recipe Title:</span> {{recipe.product_name}}</p>
                    <p><span>Recipe Category: </span> {{recipe.category}}</p>
                    <p> <span>Recipe Author: </span> {{recipe.author}}</p>
                    <p> <span>Recipe description:  </span> {{recipe.description}}</p>
                    <p> <span> Recipe ingredients:</span>  {{recipe.ingredients}}</p>
                    <p> <span>Recipe instructions: </span> {{recipe.instructions}}</p>
                  </div>

                 </div> <!-- col.// -->
            </div>



            <style>
                
                *{
                  margin: 0;
                  padding: 0;
                  box-sizing: border-box;
                }

                .row{
                  width: 100%;
                }

                .card-img{
                  /* display: flex; */
                  width: 100%;
                  text-align: center;
                  background-color: aliceblue;
                }
                
                .img-wrap img{
                  border-radius: 30px;
                  width: 50%;
                  height: 400px;
                  padding: 20px;
                }

                /* information design start from here */
                    .info-body{
                      width: 100%;
                      background-color: rgb(243, 241, 239);
                      text-align: left
  
                    }

                    .card-info-details{
                      width: 80%;
                      margin-left: 20px;
                      padding: 10px;
                      text-align: justify;
                    }

                    .card-info-details p{
                      padding: 10px;
                      font-size: 1.2rem;
                    }

                    .card-info-details p span{
                      font-weight: bold;
                    }
                /* information design ended here */
            </style>
          

{% endblock%}

store/templates/update_recipe.html
{% extends 'base.html' %}

{% block body%}
<section class="section-containers">
      <!-- ============================ COMPONENT REGISTER   ================================= -->
      <div class="card-sections">
        <div class="card-body">
          <header>
            <h4 class="card-title"></h4>
          </header>
          <div class="form-div">
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-row">
                <div class="col form-group">
                  <label>Item name</label>
                  <br/>
                  <p class="product-class">{{form.product_name}}</p>
                  <br>
                </div>
              </div>
  
  
                <div class="col form-group">
                  <label>Category</label>
                  <br/>
                  <p class="product-class">{{ form.category }}</p>
                </div>
                <!-- form-group end.// -->
                <div class="col form-group">
                 
                  <label>Description</label>
                  <br/>
                  <p class="product-class">{{form.description}}</p>
           
                <!-- form-group end.// -->
              </div>
              <!-- form-row end.// -->
              <div class="form-group">
                <label>Ingredients</label>
                <br/>
                  <p class="product-class">{{form.ingredients}}</p>
              </div>
              <!-- form-group end.// -->
  
           
                <div class="form-group col-md-6">
                  <label>Instructions</label>
                  <br/>
                   <p class="product-class">{{form.instructions}}</p>
                  <br/>
                </div>
                <!-- form-group end.// -->
                <div class="form-group col-md-6">
                  <label>image</label>
                  <br/>
             
                  <p class="product-class">{{form.image}}</p>
                </div>
                <!-- form-group end.// -->
              
              <div class="form-group">
                <button type="submit" class="btn-block">
                  Submit
                </button>
              </div>
              <!-- form-group// -->
            </form>
          </div>


        </div>
        <!-- card-body.// -->
      </div>
      <!-- card .// -->

      <br /><br />
      <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    </section>


    <style>

      *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      .section-containers{
        position: relative;
        width: 100%;
        background-color: azure;
        /* display: flex; */
        text-align: center;
        height: 800px;
      }

      .card-body{
        position: absolute;
        width: 50%;
        display: flex;
        left: 25%;
        background-color: rgb(230, 238, 238);
        flex: left;
      }

      .form-div{
        /* background-color: rebeccapurple; */
        width: 100%;
      }

      input#id_product_name{
        width: 310px;
        padding: 10px;
        outline: none;
        border: none;
        box-shadow: 2px 2px 2px 2px rgba(20, 20, 20, 0.6);
      }

      input#id_instructions{
        width: 310px;
        padding: 10px;
        outline: none;
        border: none;
        box-shadow: 2px 2px 2px 2px rgba(20, 20, 20, 0.6);
      }
     
      .product-class {
    /* Add your styles here */
    /* padding: 8px; */
    font-size: 16px;
    color: #333;
    line-height: 1.5;
    /* Add more styles as needed */
}

   .btn-block{
    width: 100px;
    margin: 15px;
    padding: 5px;
    background-color: green;
    color: white;
    cursor: pointer;
   }


    </style>
{% endblock%}